"""initial schema

Revision ID: fc6b2cebdc7d
Revises: 
Create Date: 2026-10-09 20:44:46.431218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6b2cebdc7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SIGNER', 'VERIFIER', 'AUDITOR', name='user_role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.String(length=128), nullable=False),
    sa.Column('message_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('L', sa.Integer(), nullable=False),
    sa.Column('attack_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_sid'), 'sessions', ['sid'], unique=True)
    op.create_table('ledger_blocks',
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('qber', sa.Float(), nullable=False),
    sa.Column('s_value', sa.Float(), nullable=False),
    sa.Column('enforcement_level', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('formatted_time', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.sid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('block_index')
    )
    op.create_index(op.f('ix_ledger_blocks_block_index'), 'ledger_blocks', ['block_index'], unique=False)
    op.create_index('ix_ledger_blocks_hash', 'ledger_blocks', ['block_hash'], unique=False)
    op.create_index(op.f('ix_ledger_blocks_session_id'), 'ledger_blocks', ['session_id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('qber', sa.Float(), nullable=False),
    sa.Column('e_x', sa.Float(), nullable=True),
    sa.Column('e_y', sa.Float(), nullable=True),
    sa.Column('e_z', sa.Float(), nullable=True),
    sa.Column('basis_asymmetry', sa.Float(), nullable=True),
    sa.Column('grover_score', sa.Float(), nullable=True),
    sa.Column('execution_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.sid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_session_id'), 'telemetry_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_logs_session_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_ledger_blocks_session_id'), table_name='ledger_blocks')
    op.drop_index('ix_ledger_blocks_hash', table_name='ledger_blocks')
    op.drop_index(op.f('ix_ledger_blocks_block_index'), table_name='ledger_blocks')
    op.drop_table('ledger_blocks')
    op.drop_index(op.f('ix_sessions_sid'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
